name: jumpbox

instance_groups:
- name: jumpbox
  instances: 1
  azs:       [z1]
  stemcell:  default
  networks:
    - name: default
  jobs:
    - { release: jumpbox, name: jumpbox }
    - { release: jumpbox, name: inventory }

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-xenial
           # minimum v170.x of Xenial REQUIRED
  version: latest

releases:
- name:    jumpbox
  version: 4.8.6
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.8.6/jumpbox-4.8.6.tgz
  sha1:    e8ead7fea99f5419f919365a42fb157215ddbbeb
